export default [
  {
    id: "1",
    name: "Read A Thing",
    progress: "Completed",
    score: "Submitted",
    questions: "Details",
    data: [{
      question: "What is you name?",
      answer: "Abeer",
      submitted: "Ahmed",
      status: "No",
    }],
  },
  {
    id: "1",
    name: "Read A Thing",
    progress: "InComplete",
    score: "Answer",
    questions: "Details",
    data: [{
      question: "What is you name?",
      answer: "Abeer",
      submitted: "Ahmed",
      status: "No",
    }],
  },
  {
    id: "1",
    name: "Read A Thing",
    progress: "Answet",
    score: "Submitted",
    questions: "Details",
    data: [{
      question: "What is you name?",
      answer: "Abeer",
      submitted: "Ahmed",
      status: "No",
    }],
  },
  {
    id: "1",
    name: "Read A Thing",
    progress: "Completed",
    score: "N/A",
    questions: "Details",
    data: [{
      question: "What is you name?",
      answer: "Abeer",
      submitted: "Ahmed",
      status: "No",
    }],
  },
  {
    id: "1",
    name: "Read A Thing",
    progress: "Completed",
    score: "Submitted",
    questions: "Details",
    data: [{
      question: "What is you name?",
      answer: "Abeer",
      submitted: "Ahmed",
      status: "No",
    }],
  },
  {
    id: "1",
    name: "Read A Thing",
    progress: "Completed",
    score: "Submitted",
    questions: "Details",
    data: [{
      question: "What is you name?",
      answer: "Abeer",
      submitted: "Ahmed",
      status: "No",
    }],
  },
  {
    id: "1",
    name: "Read A Thing",
    progress: "Completed",
    score: "Submitted",
    questions: "Details",
    data: [{
      question: "What is you name?",
      answer: "Abeer",
      submitted: "Ahmed",
      status: "No",
    }],
  }
]
